name: Deploy Static Site to AWS S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout do código
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    # Step 2: Setup e Build (validação dos arquivos)
    - name: Setup and Validate Files
      run: |
        echo "🔍 Validating HTML files..."
        find . -name "*.html" -type f -exec echo "Found HTML file: {}" \;
        echo "✅ Files validated successfully"
        echo "📦 Preparing for deployment..."
        
    # Step 3: Deploy para AWS S3
    - name: Deploy to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
      run: |
        echo "🚀 Starting deployment to AWS S3..."
        
        # Instala AWS CLI
        sudo apt-get update
        sudo apt-get install -y awscli
        
        # Configura AWS CLI
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION
        
        # Sync arquivos para S3
        aws s3 sync . s3://$S3_BUCKET --delete --exclude ".git/*" --exclude ".github/*" --exclude "README.md"
        
        # Configura website hosting (caso ainda não esteja configurado)
        aws s3 website s3://$S3_BUCKET --index-document index.html --error-document error.html
        
        echo "✅ Deployment completed successfully!"
        echo "🌐 Site available at: http://$S3_BUCKET.s3-website-$AWS_REGION.amazonaws.com"
